### ISSUE TITLE
一个问题想请教？

### ISSUE THREAD

**Issue by LWJ312** [wkcn/OSLabs#2]
您好！最近在写文件系统，了解您Lab8的代码后，我希望测试一下您的MiraiOS.img，
目前得到MiraiOs.img后所有指令输入都没有反应而且卡死，想问一下是和环境以及虚拟机有关吗？我看了您说不同虚拟机下效果不同..

**Comment by wkcn** [comment]
你好～
不同虚拟机的模拟性能不一样，会导致时钟中断被触发的间隔不一样，这个只会影响到动画的刷新频率，不会因为用了不同的虚拟机而卡死。

我刚重新编译了lab8的代码，并且用QEMU虚拟机，是可以正常输入指令的。我测试了输入数字，以及输入help指令，都没问题。

我现在使用的操作系统是Arch Linux，我在做实验时用的虚拟机包括QEMU, Bochs, VMware Workstaion，在这几个虚拟机下运行是没有问题的。
