### ISSUE TITLE
师兄，我有一些琐碎的问题想要请教

### ISSUE THREAD

**Issue by hhxzzy** [wkcn/OSLabs#4]
最近因为疫情没有上课，直接做实验一有一点懵。这个实验是不是需要用两台虚拟机，其中一台无操作系统，一台操作系统为DOS，然后用DOS制作一个引导盘供无操作系统的虚拟机使用？

**Comment by wkcn** [comment]
只需要一个虚拟机软件，任意虚拟机软件都可以，比如VMWare, Virtual Box, qemu, bochs, dosbox.

在Windows或者Linux系统（我使用的是Linux)编译代码，得到二进制文件。
在前面的lab1和lab2实验里，是将汇编文件编译成二进制*.bin文件；
在lab3后的实验里，是把编译出的*.bin文件放进虚拟软盘镜像里，得到disk.img文件。

然后创建一个没有操作系统的虚拟机，以用“软盘驱动器”的形式加载*.bin文件或disk.img文件。

使用qemu的话会方便一些, 比如lab1的代码：
```bash
nasm wkcn.asm -o wkcn.bin
qemu-system-x86_64 wkcn.bin
```

汇编语言的编译器可以使用：
Linux下：nasm
Windows下：masm
这两个编译器用的汇编有一点点差别，但大部分还是相同的。

高级语言建议用C语言而不是C++，因为C++的一些特性会导致坑很多。
Linux下：32位gcc即可
Windows下：我记得老师推荐的好像是tcc, 用gcc应该也没问题

虚拟机：
Linux下：qemu
Windows下：dosbox
调试用bochs

**Comment by hhxzzy** [comment]
谢谢师兄，太用心了！
我现在在Windows系统用VMWare创建了没有操作系统的虚拟机，现在还是对接下来要做什么有些困惑。
大概有这些问题：
1.如果我要让一个没有操作系统的虚拟机显示某些图案，是不是要写一个“引导扇区程序”让虚拟机一开机就执行这个程序？
2.“引导扇区程序”和软盘驱动器是什么关系？
3.这个“引导扇区程序”是不是就是二进制文件*.bin？
4.二进制文件*.bin要放在哪里才能使虚拟机开机时执行它？
感激不尽~

**Comment by wkcn** [comment]
1. 是的。需要用汇编写一个引导扇区程序，这个程序会被加载到内存0x7c00处，程序大小为512字节并以0xaa55结束。可以补0补满512个字节。我的lab1代码是将数据段ds设为0x07c0，也可以用org 0x7c00的方式说明程序要加载的位置。

2. 虚拟机的软盘驱动器会读取img镜像文件或bin文件，文件二进制的前512个字节是引导扇区程序的指令，虚拟机会执行这些指令。

3. 是的。

4. 虚拟机软盘驱动器选择bin文件作为镜像文件即可，虽然软盘驱动器要求img文件，选“显示所有文件“后再选择bin文件即可。

**Comment by hhxzzy** [comment]
谢谢师兄，我大概明白了！
